# LENGTH for x-direction, WIDTH for y-direction

# OFFICE
OFFICE_LENGTH = 8
OFFICE_WIDTH = 10

# DESK and CHAIR
DESK_LENGTH = 2
DESK_WIDTH = 1
CHAIR_RADIUS = 0.25
WHEEL_RADIUS = 0.05
NUMBER_OF_WHEELS = 5

# MOVABLE WALL
MOVABLE_WALL_LENGTH = 2
MOVABLE_WALL_WIDTH = 0.3
MOVEABLE_WALL_COLOR = ['red', 'orange', 'gold', 'lime', 'green', 'blue', 'purple', 'cyan',  'magenta']

# ORIENTATION REPRESENTATION
ORIENTATION_UP = 'UP'
ORIENTATION_DOWN = 'DOWN'
ORIENTATION_LEFT = 'LEFT'
ORIENTATION_RIGHT = 'RIGHT'

# SHAPES
OFFICE_RECTANGLE = 'RECTANGLE'
OFFICE_POLYGON = 'POLYGON'
OBJECT_RECTANGLE = 'RECTANGLE'
OBJECT_POLYGON = 'POLYGON'
OBJECT_ROUND = 'ROUND'

# ROTATION
CLOCKWISE = 'CLOCKWISE'
COUNTERCLOCKWISE = 'COUNTERCLOCKWISE'

# PROMPT
PROMPT_FULL_TEXT = 'FULL TEXT'
PROMPT_BULLET_POINTS = 'BULLET POINTS'
PROMPT_GRID = 'GRID'
PROMPT_JSON = 'JSON'

# COLLISIONS
WALL_COLLISION = 'WALL COLLISION'
DOOR_COLLISION = 'DOOR COLLISION'
DESK_COLLISION = 'DESK COLLISION'
CHAIR_COLLISION = 'CHAIR COLLISION'
PERSON_COLLISION = 'PERSON COLLISION'
OBJECT_COLLISION = 'OBJECT COLLISION'
MOVABLE_WALL_COLLISION = 'MOVABLE WALL COLLISION'

# VISUALIZATION
VISUALIZE_AS_ONE_IMAGE = 'VISUALIZE AS ONE IMAGE'
VISUALIZE_AS_MULTIPLE_IMAGES = 'VISUALIZE AS MULTIPLE IMAGES'

# CURRENT
CURRENT_OFFICE_PLAN = 4
CURRENT_PROMPT_TYPE = PROMPT_JSON
NUMBER_OF_MOVABLE_WALLS = 2
LLM_VISUALIZATION = VISUALIZE_AS_MULTIPLE_IMAGES
VISUALIZE_ONLY_VALID_SOLUTIONS = False
FOLDERNAME = 'images'

